language: ruby
rvm:
  - ree
  - 1.9.3
  - 2.0.0
gemfile:
  - gemfiles/rails2.gemfile
  - gemfiles/rails30.gemfile
  - gemfiles/rails32.gemfile
matrix:
  exclude:
    - rvm: ree
      gemfile: gemfiles/rails30.gemfile
    - rvm: ree
      gemfile: gemfiles/rails32.gemfile
    - rvm: 2.0
      gemfile: gemfiles/rails2.gemfile
    - rvm: 2.0
      gemfile: gemfiles/rails30.gemfile
script: "rake test"
